CREATE SCHEMA SISIDANG;

CREATE TABLE SISIDANG.MAHASISWA
(
	NPM CHAR(10) PRIMARY KEY NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Email_alternatif VARCHAR(100),
	Telepon VARCHAR(100),
	NoTelp VARCHAR(100)
);

CREATE TABLE SISIDANG.TERM
(
	Tahun INTEGER NOT NULL,
	Semester INTEGER NOT NULL,
	PRIMARY KEY(Tahun, Semester),
	UNIQUE (Tahun, Semester)
);

CREATE TABLE SISIDANG.PRODI
(
	ID INTEGER NOT NULL,
	NamaProdi VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID, NamaProdi)
);

CREATE TABLE SISIDANG.DOSEN
(
	NIP VARCHAR(20) PRIMARY KEY NOT NULL,
	Nama VARCHAR(100) NOT NULL,
	Username VARCHAR(50) NOT NULL,
	Password  VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Institusi VARCHAR(100) NOT NULL
);



CREATE TABLE SISIDANG.JENISMKS
(
	ID INTEGER NOT NULL PRIMARY KEY,
	NamaMKS VARCHAR(50) NOT NULL,
	UNIQUE (NamaMKS)
);

CREATE TABLE SISIDANG.MATA_KULIAH_SPESIAL
(
	IdMKS INTEGER NOT NULL,
	NPM CHAR(10) REFERENCES SISIDANG.MAHASISWA(NPM),
	Tahun INTEGER,
	Semester INTEGER,
	Judul VARCHAR(250) NOT NULL,
	IsSiapSidang BOOLEAN DEFAULT FALSE,
	PengumpulanHardCopy BOOLEAN DEFAULT FALSE,
	IjinMajuSidang BOOLEAN DEFAULT FALSE,
	IdJenisMKS INTEGER REFERENCES SISIDANG.JENISMKS(Id),
	PRIMARY KEY(IdMKS, NPM, Tahun, Semester),
	FOREIGN KEY (Tahun, Semester) REFERENCES SISIDANG.TERM (Tahun, Semester),
	UNIQUE (IdMKS)
);

CREATE TABLE SISIDANG.DOSEN_PEMBIMBING
(
	IDMKS INTEGER NOT NULL REFERENCES SISIDANG.MATA_KULIAH_SPESIAL(IDMKS),
	NIPDosenPembimbing VARCHAR(20) REFERENCES SISIDANG.DOSEN(NIP),
	PRIMARY KEY (IDMKS, NIPDosenPembimbing)
);

CREATE TABLE SISIDANG.SARAN_DOSEN_PENGUJI
(
	IDMKS INTEGER NOT NULL REFERENCES SISIDANG.MATA_KULIAH_SPESIAL(IDMKS),
	NIPSaranPenguji VARCHAR(20) REFERENCES SISIDANG.DOSEN(NIP),
	PRIMARY KEY(IDMKS, NIPSaranPenguji)
);

CREATE TABLE SISIDANG.DOSEN_PENGUJI
(
	IDMKS INTEGER NOT NULL REFERENCES SISIDANG.MATA_KULIAH_SPESIAL(IDMKS),
	NIPDosenPenguji VARCHAR(20) REFERENCES SISIDANG.DOSEN(NIP),
	PRIMARY KEY(IDMKS, NIPDosenPenguji)
);

CREATE TABLE SISIDANG.TIMELINE
(
	IdTimeline INTEGER PRIMARY KEY NOT NULL,
	NamaEvent VARCHAR(100) NOT NULL,
	Tanggal DATE NOT NULL,
	Tahun INTEGER NOT NULL,
	Semester INTEGER NOT NULL,
	FOREIGN KEY (Tahun, Semester) REFERENCES SISIDANG.TERM (Tahun, Semester)
);

CREATE TABLE SISIDANG.JADWAL_NON_SIDANG
(
	IdJadwal INTEGER PRIMARY KEY NOT NULL,
	TanggalMulai DATE NOT NULL,
	TanggalSelesai DATE NOT NULL,
	Alasan VARCHAR(100) NOT NULL,
	Repetisi VARCHAR(50),
	NIPDosen VARCHAR(20) NOT NULL REFERENCES SISIDANG.DOSEN(NIP)
);

CREATE TABLE SISIDANG.RUANGAN
(
	IDRuangan INTEGER PRIMARY KEY NOT NULL,
	NamaRuangan VARCHAR(20) NOT NULL,
	UNIQUE(NamaRuangan)
);

CREATE TABLE SISIDANG.JADWAL_SIDANG
(
	IdJadwal INTEGER NOT NULL,
	IdMKS INTEGER NOT NULL REFERENCES SISIDANG.MATA_KULIAH_SPESIAL(IdMKS),
	Tanggal DATE NOT NULL,
	JamMulai TIME NOT NULL,
	JamSelesai TIME NOT NULL,
	IDRuangan INTEGER NOT NULL REFERENCES SISIDANG.RUANGAN(IDRuangan),
	PRIMARY KEY(IdJadwal, IdMKS)
);

CREATE TABLE SISIDANG.BERKAS
(
	IDBerkas INTEGER NOT NULL,
	IDMKS INTEGER REFERENCES SISIDANG.MATA_KULIAH_SPESIAL(IDMKS),
	Nama VARCHAR(100) NOT NULL,
	Alamat VARCHAR(100) NOT NULL,
	PRIMARY KEY(IdBerkas, IdMKS)
);

CREATE TABLE SISIDANG.ADMIN
(
	IdAdmin INTEGER NOT NULL PRIMARY KEY,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(20) NOT NULL
);